config/routes.rb
ZenAppointmentsSite::Application.routes.draw do
  if Rails.env == 'development'
    match '/signin', to: redirect('http://127.0.0.1:3000/signin'), as: 'signin', via: :get
    match '/signup', to: redirect('http://127.0.0.1:3000/signup'), as: 'signup', via: :get
  else
    match '/signin', to: redirect('https://app.zenappointments.com/signin'), as: 'signin', via: :get
    match '/signup', to: redirect('https://app.zenappointments.com/signup'), as: 'signup', via: :get
  end

  post "/subscribe_to_beta_list", to: 'pages#subscribe_to_beta_list'
  get '/site', to: 'pages#site'
  root 'pages#index'
end

app/models/zen_mailing_list.rb
class ZenMailingList < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-_.]+@[a-z\d\-_.]+\.[a-z]+\z/i
  validates :email,       presence: true,
                          length: { minimum: 4, maximum: 100 },
                          format: { with: VALID_EMAIL_REGEX }
  #                        uniqueness: { case_sensitive: false }
  validates :active,      inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

  private
    def set_locale
      cookies.permanent[:locale] = params[:locale] if params[:locale].present?
      I18n.locale = cookies.permanent[:locale] if cookies.permanent[:locale].present?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def site
  end

  def help
  end

  def company
  end

  def press
  end

  def subscribe_to_beta_list
    @mailing_list = ZenMailingList.new(params.require(:mailing_list).permit(:email).merge(active: true))
    if @mailing_list.save
      ZenMailer.subscribe_to_beta_list(@mailing_list.email).deliver
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    'ZenAppointments'
  end

  def www_url
    if Rails.env == 'development' or Rails.env == 'test'
      'http://127.0.0.1:4000'
    else
      'http://www.zenappointments.com'
    end
  end

  def title
    if @title.nil?
      app_name
    else
      app_name + ' | ' + @title
    end
  end

  def active(cntrl_name)
    if cntrl_name == controller.controller_name + '#' + controller.action_name then
      return 'active'
    end
  end

  def error_class(h, sym)
    unless h.nil?
      if h.errors.messages.has_key?(sym)
        'has-error'
      end
    end
  end

  def error_message(model, sym)
    unless model.nil?
      if model.errors.messages.has_key?(sym)
        model.errors.messages[sym][0].capitalize unless model.errors.messages[sym][0].nil?
      end
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_google_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45441602-1', 'zenappointments.com');
  ga('send', 'pageview');

app/views/layouts/_signinup_menu.html.haml
-# TODO does not align with site_menu
.navbar.navbar-default.zen-navbar(role='navigation')
  .container
    .navbar-inner
      =link_to image_tag('zen-logo.png', id:'zen-logo') + ' ' + app_name, www_url, {class:'navbar-brand'}

app/views/layouts/_site_menu.html.haml
-# TODO does not align with signinup_menu
%header
  .navbar.navbar-default.zen-navbar(role='navigation')
    .container
      .navbar-inner
        -# TODO need to define app_name url
        =link_to image_tag('zen-logo.png', id:'zen-logo') + ' ' + app_name, www_url, {class:'navbar-brand'}
        %ul.nav.navbar-nav
          %li{:class => active('site#features'), id: 'features_link'}
            =link_to 'Features', '#features', class: 'scroll'
          %li{:class => active('site#pricing'), id: 'pricing_link'}
            =link_to 'Pricing', '#pricing', class: 'scroll'
          %li{:class => active('site#blog'), id: 'blog_link'}
            =link_to 'Blog', '#'
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{href: signup_path, id: 'navbar-signup'}
              %button.btn.btn-default.navbar-btn Join Now for Free!
          %li
            %a{href: signin_path, id: 'navbar-signin'}
              %button.btn.btn-default.navbar-btn Sign In
          -#%li
            -#%button.btn.btn-default.navbar-btn
              =link_to 'Join Now!', signup_path
              -#Join Now!
            -#, signup_path, class: 'btn btn-default navbar-btn'
            -#=link_to 'Join Now!', signup_path, class: 'btn btn-default navbar-btn'
            %a{href: signup_path}
              %button.btn.btn-default.navbar-btn Join Now!
            -#=link_to 'Join Now!', signup_path, class: 'btn btn-default navbar-btn'
          -#%li
            %button.btn.btn-default.navbar-btn Sign In
            -#=link_to 'Sign In', signin_path, class: 'btn btn-default navbar-btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      =title
    =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'true'
    =javascript_include_tag 'application', 'data-turbolinks-track' => 'true'
    =favicon_link_tag
    =csrf_meta_tags
  %body
    =yield
    =render('layouts/google_analytics') unless Rails.env.development?

app/views/pages/_subscribe_to_beta_list_form.html.haml
.zen-signup-beta-list
  %h4.centered
    =t '.subscribe_msg'
  =form_tag subscribe_to_beta_list_path, method: :post, data: {remote: true} do |f|
    .row
      .col-sm-6.col-sm-offset-2
        .form-group#email{class: error_class(@mailing_list, :email)}
          %input.form-control#email{placeholder: t('.your_email'), name: 'mailing_list[email]', type: 'text'}
          -unless error_message(@mailing_list, :email).nil?
            %p.help-block#email
              %i.fa.fa-exclamation-triangle
              =error_message(@mailing_list, :email)
      .col-sm-2
        =submit_tag(t('.subscribe_btn'), class: 'btn btn-primary', 'data-disable-with' => t('.subscribing_btn') + ' ...')

app/views/pages/help.html.haml
%h1 help

app/views/pages/index.html.haml
=render('layouts/signinup_menu')
.container
  .zen-hero-section
    %h1.centered
      =app_name
      =t'.main_title'
    %br
    %h3.centered
      =t'.main_subtitle'

  .well
    =render('subscribe_to_beta_list_form')

.chessboard
  .container
    .row
      %h2.centered
        =t'.everything_you_need'
      .col-sm-3.centered
        %i.fa.fa-calendar.icon-big
        %h3.centered
          =t'.schedule_clients'
      .col-sm-3.centered
        %i.fa.fa-group.icon-big
        %h3.centered
          =t'.manage_client_list'
      .col-sm-3.centered
        %i.fa.fa-bell.icon-big
        %h3.centered
          =t'.send_auto_reminders'
      .col-sm-3.centered
        %i.fa.fa-money.icon-big
        %h3.centered
          =t'.track_your_billing'
    .row
      .col-sm-3.centered
        %i.fa.fa-mobile-phone.icon-big
        %h3.centered
          =t'.check_schedule'
      .col-sm-3.centered
        %i.fa.fa-lock.icon-big
        %h3.centered
          =t'.secure'
      .col-sm-3.centered
        %i.fa.fa-cloud.icon-big
        %h3.centered
          =t'.always_backed_up'
      .col-sm-3.centered
        %i.fa.fa-bar-chart-o.icon-big
        %h3.centered
          =t'.measure_your_business'
.footer
  .container
    .row
      .col-sm-6
        %h5
          =app_name
        %p
          =t'.main_subtitle'
      .col-sm-6
        %h5
          =t'.contact_us'
        %p
          %span.fa.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-twitter.fa-stack-1x.fa-inverse
          twitter
        %p
          %span.fa.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-facebook.fa-stack-1x.fa-inverse
          facebook
        %p
          %span.fa.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-google-plus.fa-stack-1x.fa-inverse
          google+
        %p
          %span.fa.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-envelope-o.fa-stack-1x.fa-inverse
          email

  %p
    #lang-links
      =link_to_unless_current 'en', locale: 'en'#, {class: 'link'}
      |
      =link_to_unless_current 'pt-br', locale: 'pt-BR'#, {class: 'link'}
    #footer-links
      =link_to 'site', site_path, {class: 'link'}
      |
      =link_to 'sign in', signin_path, {class: 'link'}

app/views/pages/site.html.haml
=render('layouts/site_menu')
.container
  .row
    .col-lg-12
      .jumbotron.homepage
        =image_tag 'http://placehold.it/980x500', class: 'bg'
        .content
          %h1 Everything you need to schedule your clients
          =link_to 'Join now for free!', signup_path, class: 'large radius nice blue button'
.acme-demo
  .container
    .row
      .col-lg-12
        %h2.centered elegant software to manage your office
        .acme-demo-container
          -#.explanations
            %ul
              %li foo 1
              %li foo 2
              %li foo 3
              %li foo 4
.chessboard
  .container
    .row
      %h2.centered Everything you need to schedule your clients
      .col-sm-3.centered
        %i.fa.fa-calendar.icon-big
        %h3.centered
          Schedule Clients
      .col-sm-3.centered
        %i.fa.fa-group.icon-big
        %h3.centered
          Manage your Client List
      .col-sm-3.centered
        %i.fa.fa-bell.icon-big
        %h3.centered
          Send Automatic Reminders to Your Clients
      .col-sm-3.centered
        %i.fa.fa-money.icon-big
        %h3.centered
          Tracking Your Billing
    .row
      .col-sm-3.centered
        %i.fa.fa-mobile-phone.icon-big
        %h3.centered
          Check your schedule on the run
      .col-sm-3.centered
        %i.fa.fa-lock.icon-big
        %h3.centered
          Secure
      .col-sm-3.centered
        %i.fa.fa-cloud.icon-big
        %h3.centered
          Always backed up so you never lose anything
      .col-sm-3.centered
        %i.fa.fa-bar-chart-o.icon-big
        %h3.centered
          Measure how your business is doing
.features#features
  %a{name: 'features'}
  .container
    .row
      %a{name: 'features'}
      %h2.centered Features
      .col-sm-6.centered
        =image_tag 'http://placehold.it/400x300'
        %h4
          Integer diam magna, lobortis eget fermentum sit amet
      .col-sm-6.centered
        =image_tag 'http://placehold.it/400x300'
        %h4
          Iaculis eget sem. Pellentesque non lacinia est, et posuere sem
    .row
      .col-sm-6.centered
        =image_tag 'http://placehold.it/400x300'
        %h4
          Integer diam magna, lobortis eget fermentum sit amet
      .col-sm-6.centered
        =image_tag 'http://placehold.it/400x300'
        %h4
          Iaculis eget sem. Pellentesque non lacinia est, et posuere sem
.social
  .container
    .row
      .col-sm-8
        %h2 Happy Customers
        .row
          .col-sm-4
            =image_tag 'http://placehold.it/200x200'
          .col-sm-8
            %p
              Iaculis eget sem. Pellentesque non lacinia est, et posuere sem
              Integer diam magna, lobortis eget fermentum sit amet

            %strong
              Lucteticus Sindimus
        %br
        .row
          .col-sm-4
            =image_tag 'http://placehold.it/200x200'
          .col-sm-8
            %p
              Integer diam magna, lobortis eget fermentum sit amet
              Iaculis eget sem. Pellentesque non lacinia est, et posuere sem
            %strong
              Founder's Mom
      .col-sm-4
        %h2 Twitter
        .row
          .col-sm-4
            =image_tag 'http://placehold.it/75x75'
          .col-sm-8
            Iaculis eget sem. Pellentesque non lacinia est, et posuere sem
            %strong
              Founder's Mom
        %br
        .row
          .col-sm-4
            =image_tag 'http://placehold.it/75x75'
          .col-sm-8
            Iaculis eget sem. Pellentesque non lacinia est, et posuere sem
            %strong
              Founder's Mom
        %br
        .row
          .col-sm-4
            =image_tag 'http://placehold.it/75x75'
          .col-sm-8
            Iaculis eget sem. Pellentesque non lacinia est, et posuere sem
            %strong
              Founder's Mom
        %br
        .row
          .col-sm-4
            =image_tag 'http://placehold.it/75x75'
          .col-sm-8
            Iaculis eget sem. Pellentesque non lacinia est, et posuere sem
            %strong
              Founder's Mom
.pricing#pricing
  %a{name: 'pricing'}
  .container
    .row
      %a{name: 'pricing'}
      %h2.centered
        Pricing
      .centered
        .btn-group
          %button.btn.btn-default.btn-price-monthly
            Monthly
          %button.btn.btn-default.btn-price-yearly
            Yearly
    .row
      .col-sm-12
        %ul.pricing-table
          %li.title Basic
          %li.price.monthly
            $&nbsp;12.95/month
          %li.price.yearly
            $&nbsp;9.95/month
            .yearly-details
              One payment of $&nbsp;119,40
          %li.description Single User
          %li.bullet-item Unlimited Clients
          %li.bullet-item Unlimited Appointments
          %li.bullet-item Single Employee
          %li.bullet-item Simple Reports
          %li.bullet-item No Detailed Reports
          %li.bullet-item No Billing
          %li.bullet-item No Auto Reminders by Email
          %li.bullet-item No Auto Reminders by SMS
          %li.bullet-item Web Only
          %li.button
            =link_to 'Join Now!', signup_path, class: 'btn btn-primary'
        %ul.pricing-table
          %li.title Solo
          %li.price.monthly
            $&nbsp;33.95/month
          %li.price.yearly
            $&nbsp;29.95/month
            .yearly-details
              One payment of $&nbsp;359,40
          %li.description Single User
          %li.bullet-item Unlimited Clients
          %li.bullet-item Unlimited Appointments
          %li.bullet-item Single Employee
          %li.bullet-item Simple Reports
          %li.bullet-item Detailed Reports
          %li.bullet-item Billing
          %li.bullet-item Auto Reminders by Email
          %li.bullet-item No Auto Reminders by SMS
          %li.bullet-item Web/Mobile
          %li.button
            =link_to 'Join Now!', signup_path, class: 'btn btn-primary'
        %ul.pricing-table
          %li.title Small Office
          %li.price.monthly
            $&nbsp;85.95/month
          %li.price.yearly
            $&nbsp;79.95/month
            .yearly-details
              One payment of $&nbsp;959,40
          %li.description Multi User
          %li.bullet-item Unlimited Clients
          %li.bullet-item Unlimited Appointments
          %li.bullet-item 10 Employees
          %li.bullet-item Simple Reports
          %li.bullet-item Detailed Reports
          %li.bullet-item Billing
          %li.bullet-item Auto Reminders by Email
          %li.bullet-item Auto Reminders by SMS
          %li.bullet-item Web/Mobile
          %li.button
            =link_to 'Join Now!', signup_path, class: 'btn btn-primary'
        %ul.pricing-table
          %li.title Big Office
          %li.price.monthly
            $&nbsp;289.95/month
          %li.price.yearly
            $&nbsp;249.95/month
            .yearly-details
              One payment of $&nbsp;2.999,40
          %li.description Multi User
          %li.bullet-item Unlimited Clients
          %li.bullet-item Unlimited Appointments
          %li.bullet-item Unlimited Employee
          %li.bullet-item Simple Reports
          %li.bullet-item Detailed Reports
          %li.bullet-item Billing
          %li.bullet-item Auto Reminders by Email
          %li.bullet-item Auto Reminders by SMS
          %li.bullet-item Web/Mobile
          %li.button
            =link_to 'Join Now!', signup_path, class: 'btn btn-primary'
        %ul.pricing-table
          %li.title Multi Office
          %li.price.monthly
            $&nbsp;105.95/month*
          %li.price.yearly
            $&nbsp;89.95/month*
            .yearly-details
              One payment of $&nbsp;1.079,40
          %li.description Multi User
          %li.bullet-item Unlimited Clients
          %li.bullet-item Unlimited Appointments
          %li.bullet-item Unlimited Employee
          %li.bullet-item Simple Reports
          %li.bullet-item Detailed Reports
          %li.bullet-item Billing
          %li.bullet-item Auto Reminders by Email
          %li.bullet-item Auto Reminders by SMS
          %li.bullet-item Web/Mobile
          %li.button
            =link_to 'Join Now!', signup_path, class: 'btn btn-primary'
.footer
  .container
    .row
      .col-sm-6
        %h5
          =app_name
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit
        -# Company Press Blog
      .col-sm-6
        %h5 Contact Us
        %p
          %span.fa.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-twitter.fa-stack-1x.fa-inverse
          twitter
        %p
          %span.fa.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-facebook.fa-stack-1x.fa-inverse
          facebook
        %p
          %span.fa.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-google-plus.fa-stack-1x.fa-inverse
          google+
        %p
          %span.fa.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-envelope-o.fa-stack-1x.fa-inverse
          email

app/views/pages/subscribe_to_beta_list.js.haml
-if @mailing_list.valid?
  $('.zen-signup-beta-list').replaceWith("<h3>#{t('.thank_you_scribing')}</h3>");
-else
  $('.zen-signup-beta-list').replaceWith("#{j render('subscribe_to_beta_list_form')}");